### ISSUE TITLE
Version and tar.gz

### ISSUE THREAD

**Issue by maxim092001** [jmid/mutaml#14]
Hey!

I couldn't find a current version for mutaml either in tags/releases tab as well as link to tar.gz of particular version. Would it be possible to create some release (0.1 or any other)? It blocks us from using mutaml internally. 

I would be happy to help with that and further issues as well!

Thanks.

**Comment by jmid** [comment]
Thanks for your interest and the encouragement! :smiley: 
I'll try to roll an official 0.1 release later this week.

**Comment by jmid** [comment]
I've now published an initial 0.1 opam release: https://github.com/jmid/mutaml/releases/tag/0.1

**Comment by maxim092001** [comment]
> I've now published an initial 0.1 opam release: https://github.com/jmid/mutaml/releases/tag/0.1

Thanks!
