### ISSUE TITLE
conf-* dependencies

### ISSUE THREAD

**Issue by maxim092001** [jmid/mutaml#24]
Hey.

What are these three dependencies:

-   "conf-timeout"
-   "conf-which"
-   "conf-diffutils"

I found them in `opam`, but didn't find the source repo and usages of them in mutaml. Can you please explain to me what they are actually doing and point out to repo?

**Comment by jmid** [comment]
They are small opam repository packages to check for the 3 commands `timeout`, `which`, and `diffutils`.

For each package, the source code consists of a single opam file available in
https://github.com/ocaml/opam-repository/tree/master/packages/conf-timeout
https://github.com/ocaml/opam-repository/tree/master/packages/conf-which
https://github.com/ocaml/opam-repository/tree/master/packages/conf-diffutils

Each opam file lists the external dependencies (`depexts`) required to ensure that each of them is installed, e.g., the `coreutils` Debian package to ensure `timeout` is available.

**Comment by maxim092001** [comment]
> They are small opam repository packages to check for the 3 commands `timeout`, `which`, and `diffutils`.
> 
> For each package, the source code consists of a single opam file available in https://github.com/ocaml/opam-repository/tree/master/packages/conf-timeout https://github.com/ocaml/opam-repository/tree/master/packages/conf-which https://github.com/ocaml/opam-repository/tree/master/packages/conf-diffutils
> 
> Each opam file lists the external dependencies (`depexts`) required to ensure that each of them is installed, e.g., the `coreutils` Debian package to ensure `timeout` is available.

Didn't know about `conf-*` packages before, thank you for explanation!
