### ISSUE TITLE
select mutation files from command-line

### ISSUE THREAD

**Issue by raphael-proust** [jmid/mutaml#5]
When running `mutaml-runner` it would be interesting to select mutation files from the command line (`mutaml-runner --muts src/foo.muts "…"`) rather than having them selected from the contents of the `mutaml-mut-files.txt` file.

The reason this would be useful is that some test executables may exercise some parts of the code-base only. There is no point in trying mutations in files unrelated to the tests that are being run.

Right now I work around this by editing the `mutaml-mut-files.txt` file, running one test executable, re-editing to select a different set of mutations. running a different test executable, etc. Being able to run the following instead would be useful.

```
mutaml-runner --muts src/foo.muts "dune exec test/test_foo.exe"
mutaml-runner --muts src/bar_blah.muts,src/bar_blob.muts "dune exec test/test_bar.exe"
```

(Even better would be to pass mutaml-runner a mapping of test executables to source files and have it consume that. But it is significantly more work, and the `--muts` parameter would already solve the core issue.)

**Comment by jmid** [comment]
Acknowledged :+1:  I agree that a `--muts` parameter should both be usable and doable without too much effort.
Your second suggestion would indeed be even better.
